Loaded checkpoint gp_mobilenet_v2_DH0.9_DL1.0_W0.35_local_1x2_T at epoch 2.
Files already downloaded and verified
Files already downloaded and verified
Start group-level pruning version training.
Start validation after calibration.
Traceback (most recent call last):
  File "train.py", line 629, in <module>
    main()
  File "train.py", line 627, in main
    train_val_test()
  File "train.py", line 611, in train_val_test
    eval_width=width_cal, eval_density=density_cal)
  File "train.py", line 350, in run_one_epoch
    model.apply(bn_calibration_init)
NameError: name 'bn_calibration_init' is not defined
Traceback (most recent call last):
  File "train.py", line 629, in <module>
    main()
  File "train.py", line 627, in main
    train_val_test()
  File "train.py", line 611, in train_val_test
    eval_width=width_cal, eval_density=density_cal)
  File "train.py", line 350, in run_one_epoch
    model.apply(bn_calibration_init)
NameError: name 'bn_calibration_init' is not defined